### ISSUE TITLE
Corrplot.mixed & plotCI

### ISSUE THREAD

**Issue by behinger** [taiyun/corrplot#21] opened 2016-02-11 16:42 UTC
currently `corrplot.mixed` and `plotCI` are not really compatible.

``` r
corrplot::corrplot.mixed(M,lower='number',upper='circle',low=L,upp=U,plotCI='rect')
```
results in the following error:
```
Error in corrplot(corr, add = TRUE, type = "lower", method = lower, diag = (diag ==  : 
method should be circle or square if draw confidence interval!
```
And only draws the upper half with confidence plots.
It should also draw the lower triangle with numbers.

It is also currently not clear how to specify which (the upper or lower) triangle to be used by "rect"

**Comment by vsimko** [comment] 2016-03-15 16:36
Could you provide a reproducible example ?
What are the object `M`, `L` and `U` ?

**Comment by behinger** [comment] 2016-03-15 16:40
Here is the example (using corrplot_0.73)
```
M <- cor(mtcars)
L <- M-0.01
U <- M+0.01
corrplot::corrplot.mixed(M,lower='number',upper='circle',low=L,upp=U,plotCI='rect')
```
This results in:
> Error in corrplot(corr, add = TRUE, type = "lower", method = lower, diag = (diag ==  :   method shoud be circle or square if draw confidence interval!

**Comment by vsimko** [comment] 2016-03-15 17:54
I fixed the error for now, but further API redesign is needed, I think.
Here is the output generated from your example code:
![image](https://cloud.githubusercontent.com/assets/7080773/13788181/151e2924-eadf-11e5-846a-99261aea7f8f.png)

Please confirm whether this is the expected output.
If yes, please create a new issue and suggest the API change.

**Comment by behinger** [comment] 2016-03-16 08:47
This indeed works for me! 

It only works for numbers though. Other cases:

`corrplot::corrplot.mixed(M,lower='circle',upper='square',low=L,upp=U,plotCI='rect')` 
(lower boxplot, upper boxplot - expected: lower circle, upper boxplot)

`corrplot::corrplot.mixed(M,lower='ellipse',upper='square',low=L,upp=U,plotCI='rect')` 
(lower empty, upper boxplot - expected: lower ellipse, upper boxplot)

`corrplot::corrplot.mixed(M,lower='pie',upper='square',low=L,upp=U,plotCI='rect')`
results in:
> Error in corrplot(corr, add = TRUE, type = "lower", method = lower, diag = (diag ==  : 
>   method shoud be circle or square if draw confidence interval!


I am not sure what kind of API redesign you are thinking of because I did not look into the underlying code. It is probably more helpful if you post the api change, because you know what needs to change in the api.

**Comment by vsimko** [comment] 2016-03-16 15:51
I'm closing this for now, because it seems that I covered the use-case with my latest fix.

**Closed by vsimko** 2016-03-16 15:51 UTC
Labels: bug
